package vsphere_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type VsphereCpi struct {

	/*Blobstore - Descr: Password agent uses to connect to blobstore used by simple blobstore plugin Default: <nil>
*/
	Blobstore Blobstore `yaml:"blobstore,omitempty"`

	/*Env - Descr: No Proxy environment variable Default: <nil>
*/
	Env Env `yaml:"env,omitempty"`

	/*Nats - Descr: Address of the nats server Default: <nil>
*/
	Nats Nats `yaml:"nats,omitempty"`

	/*Vcenter - Descr: Password to connect to vCenter server used by vspher cpi Default: <nil>
*/
	Vcenter Vcenter `yaml:"vcenter,omitempty"`

	/*Ntp - Descr: List of ntp server IPs. pool.ntp.org attempts to return IPs closest to your location, but you can still specify if needed. Default: [0.pool.ntp.org 1.pool.ntp.org]
*/
	Ntp interface{} `yaml:"ntp,omitempty"`

	/*Agent - Descr: Signature version used to connect to an s3 blobstore Default: <nil>
*/
	Agent Agent `yaml:"agent,omitempty"`

}