package aws_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AwsCpi struct {

	/*Env - Descr: Https proxy to connect to cloud API's Default: <nil>
*/
	Env Env `yaml:"env,omitempty"`

	/*Ntp - Descr: List of ntp server IPs. pool.ntp.org attempts to return IPs closest to your location, but you can still specify if needed. Default: [0.pool.ntp.org 1.pool.ntp.org]
*/
	Ntp interface{} `yaml:"ntp,omitempty"`

	/*Aws - Descr: AWS kernel id used by aws cpi Default: <nil>
*/
	Aws Aws `yaml:"aws,omitempty"`

	/*Agent - Descr: Address of the nats server Default: <nil>
*/
	Agent Agent `yaml:"agent,omitempty"`

	/*Blobstore - Descr: Host of blobstore server used by simple blobstore plugin Default: <nil>
*/
	Blobstore Blobstore `yaml:"blobstore,omitempty"`

	/*Registry - Descr: Password to access the Registry Default: <nil>
*/
	Registry Registry `yaml:"registry,omitempty"`

	/*Nats - Descr: Port that the nats server listens on Default: 4222
*/
	Nats Nats `yaml:"nats,omitempty"`

}