package openstack_cpi 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type OpenstackCpi struct {

	/*Openstack - Descr: URL of the OpenStack Identity endpoint to connect to (required) Default: <nil>
*/
	Openstack Openstack `yaml:"openstack,omitempty"`

	/*Registry - Descr: Address of the Registry to connect to (required) Default: <nil>
*/
	Registry Registry `yaml:"registry,omitempty"`

	/*Ntp - Descr: List of NTP servers Default: []
*/
	Ntp interface{} `yaml:"ntp,omitempty"`

	/*Nats - Descr: NATS address used by agent to subscribe to agent requests Default: <nil>
*/
	Nats Nats `yaml:"nats,omitempty"`

	/*Env - Descr: Http proxy to connect to cloud API's Default: <nil>
*/
	Env Env `yaml:"env,omitempty"`

	/*Agent - Descr: AWS region for agent used by s3 blobstore plugin Default: <nil>
*/
	Agent Agent `yaml:"agent,omitempty"`

	/*Blobstore - Descr: Provider of the blobstore used by director and agent (simple|local) Default: <nil>
*/
	Blobstore Blobstore `yaml:"blobstore,omitempty"`

}