package atc 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Postgresql struct {

	/*Address - Descr: Address of a PostgreSQL server to connect to, in `HOST:PORT` format.

If not specified, one will be autodiscovered via BOSH links.
 Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*Role - Descr: Password to use when connecting.
 Default: <nil>
*/
	Role Role `yaml:"role,omitempty"`

	/*Database - Descr: Name of the database to use.
 Default: atc
*/
	Database interface{} `yaml:"database,omitempty"`

}