package releasejobs
/*
* File Generated by enaml generator
*/
type Baggageclaim struct {

	BindIp string `yaml:"bind_ip,omitempty"`

	BindPort int `yaml:"bind_port,omitempty"`

	Yeller_apiKey string `yaml:"yeller.api_key,omitempty"`

	Yeller_environmentName string `yaml:"yeller.environment_name,omitempty"`

}