package releasejobs
/*
* File Generated by enaml generator
*/
type Blackbox struct {

	Blackbox_syslog_destination_address interface{} `yaml:"blackbox.syslog.destination.address,omitempty"`

	Blackbox_syslog_destination_transport string `yaml:"blackbox.syslog.destination.transport,omitempty"`

	Blackbox_syslog_sourceDir string `yaml:"blackbox.syslog.source_dir,omitempty"`

}