package releasejobs
/*
* File Generated by enaml generator
*/
type Groundcrew struct {

	HttpsProxyUrl interface{} `yaml:"https_proxy_url,omitempty"`

	ResourceTypes []interface {} `yaml:"resource_types,omitempty"`

	Tsa_privateKey string `yaml:"tsa.private_key,omitempty"`

	Garden_address interface{} `yaml:"garden.address,omitempty"`

	Baggageclaim_url interface{} `yaml:"baggageclaim.url,omitempty"`

	Tags []interface {} `yaml:"tags,omitempty"`

	AdditionalResourceTypes []interface {} `yaml:"additional_resource_types,omitempty"`

	Yeller_apiKey string `yaml:"yeller.api_key,omitempty"`

	Tsa_hostPublicKey string `yaml:"tsa.host_public_key,omitempty"`

	Platform string `yaml:"platform,omitempty"`

	HttpProxyUrl interface{} `yaml:"http_proxy_url,omitempty"`

	NoProxy []interface {} `yaml:"no_proxy,omitempty"`

	Tsa_port int `yaml:"tsa.port,omitempty"`

	Tsa_host interface{} `yaml:"tsa.host,omitempty"`

	Garden_forwardAddress interface{} `yaml:"garden.forward_address,omitempty"`

	Baggageclaim_forwardAddress interface{} `yaml:"baggageclaim.forward_address,omitempty"`

	Yeller_environmentName string `yaml:"yeller.environment_name,omitempty"`

}