package releasejobs
/*
* File Generated by enaml generator
*/
type Postgresql struct {

	BindIp string `yaml:"bind_ip,omitempty"`

	BindPort int `yaml:"bind_port,omitempty"`

	Databases interface{} `yaml:"databases,omitempty"`

	MaxConnections int `yaml:"max_connections,omitempty"`

}