package releasejobs
/*
* File Generated by enaml generator
*/
type Tsa struct {

	ForwardHost interface{} `yaml:"forward_host,omitempty"`

	BindPort int `yaml:"bind_port,omitempty"`

	HostKey string `yaml:"host_key,omitempty"`

	HostPublicKey string `yaml:"host_public_key,omitempty"`

	AuthorizedKeys []interface {} `yaml:"authorized_keys,omitempty"`

	HeartbeatInterval string `yaml:"heartbeat_interval,omitempty"`

	Yeller_apiKey string `yaml:"yeller.api_key,omitempty"`

	Yeller_environmentName string `yaml:"yeller.environment_name,omitempty"`

	AuthorizeGeneratedWorkerKey bool `yaml:"authorize_generated_worker_key,omitempty"`

}